spring.application.name=web_based_apartment_sales_system

spring.datasource.url=jdbc:mysql://localhost:3306/apartmentSalesSystem?createDatabaseIfNotExist=true
spring.datasource.username=
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=
jwt.expiration-ms=86400000
