spring.application.name=web_based_apartment_sales_system

spring.datasource.url=jdbc:mysql://localhost:3306/apartmentSalesSystem?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=dbbb85038dee4354fd545e1054cdb23ac4231fad5f347b2e1a9807d5a2f67cec
jwt.expiration-ms=86400000
